### ISSUE TITLE
Get Jacoco Running

### ISSUE THREAD

**Issue by zaleshaiker** [ucsb-cs56-f18/ucsb-cs56-buy-sell-giveaway#15]
Add Jacoco to the project so we can start the test case coverage

**Comment by wilsonmui** [comment]
If this is just adding some lines to your pom.xml, then it may be too small for an issue. Maybe create a new issue with using Jacocco to run tests on a specific file(?)

**Comment by pconrad** [comment]
@derektkbang Please answer the question that @wilsonmui asked you so that he can estimate this issue.

I think it's fine for 100 point issue for this to be adding the necessary stuff in the pom.xml for getting the Jacoco report to show up in the target/site/jacoco/index.html file ALONG WITH instructions, and ALONG WITH the stuff you and I found for making the `mvn site` not take so long.

But you MUST respond to the question from your mentor, and get the issue estimated and approved BEFORE you can get any points for it.  You did some good work on it, but you can't get any credit for it if you don't take the necessary project management steps.

**Comment by pconrad** [comment]
And @yinonrousso ... this should NOT be in Ready for QA, because there isn't a pull request from a branch that contains the  changes taht @derektkbang  made, along with a README.md that explains how to go about testing the work he did.

I'm dragging it back into In-Progress.  Don't put it back until you've read the two Piazza posts, and made a Pull Request.  If you need help, ask Wilson for help, or add phtcon@ucsb.edu to your slack, and ask me for help.

**Comment by wilsonmui** [comment]
100
